### ISSUE TITLE
PySTAC `Catalog.add_child()` takes progressively longer as more children are added

### ISSUE THREAD

**Issue by forrestfwilliams** [ASFHyP3/asf-stac#8]
I'm attempting to generate the STAC catalog for the entire coherence dataset on this [branch](https://github.com/ASFHyP3/asf-stac/blob/whole_word/src/coherence_stac.py). When calling  `Catalog.add_child()` to add the sub-collections, each call takes progressively longer as you add more children. When trying to add the ~25,000 sub-collections, I've killed the process after it ran for 1.5 hours. I tried using the `Catalog.add_children()` command, but had the same results. This [line](https://github.com/ASFHyP3/asf-stac/blob/0e875468ce200399154c227af72f80e8fcd3e316/src/coherence_stac.py#L297) is where we're calling the offending method.

**Comment by jhkennedy** [comment]
In `pystac`, `add_children` is just a simple loop around `add_child` so that's why it runs about the same as what you're doing. 
https://github.com/stac-utils/pystac/blob/main/pystac/catalog.py#L274-L275

From the look of [`add_child`](https://github.com/stac-utils/pystac/blob/main/pystac/catalog.py#L229-L262), all the work except the final `self.add_link` is just in the children, so I suspect you could use concurrent futures/multiprocessing here to speed it up, but might require hacking the add_child code...

**Comment by jhkennedy** [comment]
`add_link` is just a `list.append`, so totally could do this in parallel and then `extend` the list instead:
https://github.com/stac-utils/pystac/blob/main/pystac/stac_object.py#L56-L63

**Comment by jhkennedy** [comment]
Okay, I played around with this quite a bit. Notably, on my local machine even creating the items was very slow, so I gave up and fired and EC2.

On an `r5dn.xlarge` EC2 instance.

For the current `add_child` method, the timing looked like:
* Creating items: 23 minutes
* Creating catalog: 53 minutes

In #18, I was able to significantly speed up the catalog creation (~1 minute) but the `root` links were all empty. After a few iterations, I was able to get the root links back correctly, but the timing is not appreciably different than `add_child`. 

This is due to the [pystac cache](https://github.com/stac-utils/pystac/blob/main/pystac/cache.py#L36) -- every time `add_root` is called, it not only adds the root link, but it also goes through the entire root catalog's cache and adds the item if not found. So, you end up iterating through every item in the new collection, and then again, through every item in the entire catalog. As the catalog grows, that second part starts to bog down. I did not see an easy way to circumvent the cache, nor really grok the need for the cache, so I don't see a path forward for optimizing `pystac` without significant investment.

The alternate approach would be to do a fast catalog creation, not worrying about the root, save it, and then with just straight JSON tools, edit the root link manually. That likely would be super fast (~minutes) since the root links are static for any particular depth to the catalog, but significantly more brittle. 

So overall, I'm doing to close this as a `wont-do` as we won't get any significant improvement without dropping `pystac` in part or in whole. A 1.5-2 hour runtime on an EC2 doesn't seem blocking to me.

@forrestfwilliams and @jtherrmann feel free to re-open if you disagree or have other ideas to try.
